[package]
name = "lvm-homepage"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = {version = "4.12.0"}
serde = {version = "1.0.228"}
serde_json = {version = "1.0.145"}
tokio = {version = "1.48.0"}